### ISSUE TITLE
Moving Games to categories they belong.

### ISSUE THREAD

**Issue by lsmor** [haskell-game/tiny-games-hs#12]
Hi, I think the some games are wrongly labeled as `hackage` category:

- ski
- bulls-and-cows
- guess2
- wordle

they should belong to `default` category since they only use `random`package aside from base. Also I'd suggest to move every game to its own folder, hence:

- hackage/bulls-and-cows
- hackage/guess2
- hackage/wordle
- prelude/guess1
- prelude/pure-doors

should be move to individual folders

**Comment by simonmichael** [comment]
I have had some confusion about this. Originally I thought `random` was in the default packages installed with GHC. Then I found it's not, therefore I moved these to the hackage category.
