### ISSUE TITLE
Prohibit reading the comments section of the source file

### ISSUE THREAD

**Issue by kukimik** [haskell-game/tiny-games-hs#121]
Perhaps in future editions a rule should be included that the program submitted shouldn't read the comments section of the source file. This would probably by frowned upon by the judges anyway, but maybe it's worth saying explicitly.

**Comment by OsePedro** [comment]
There should also be a rule prohibiting people from creating a Hackage package that contains loads of functionality that's specific to their game, and then saying "look how short my game is: `import MyIncredibleGame; main=runMyIncredibleGame`".

**Comment by gergoerdi** [comment]
> There should also be a rule prohibiting people from creating a Hackage package that contains loads of functionality that's specific to their game, and then saying "look how short my game is: `import MyIncredibleGame; main=runMyIncredibleGame`".

I can think of three lines of defense against this one:

* Require the use of a Stackage LTS that predates the contest
* Realize that competitors are going to compete in good spirit
* Beside the main winner, also give a special "best bending of the rules" award a la IOCCC

This third "solution" also applies to reading in the source code!

**Comment by simonmichael** [comment]
Ideas noted! To allow creativity and discovery we don't want to crank down the rules too tight too soon, but will do as needed. Thanks!

**Comment by simonmichael** [comment]
PS yes, releasing a very convenient low-boilerplate game lib on Hackage would indeed have been within the contest rules - but I figured it would be not such a bad outcome!
