### ISSUE TITLE
Technically games in lighter categories also fit the heavier categories, so they should compete there as well!

### ISSUE THREAD

**Issue by kindaro** [haskell-game/tiny-games-hs#15]
Given a game that works with `Prelude` alone, surely I can:

1. Add a spurious import to put it formally into the `base` category.
2. Create a file `Imports.hs` to put it formally into the `default` category.
3. Import something weird to put it formally into the `hackage` category.

I can further obfuscate that these imports are spurious by using them in some way, I can rename the game, create fake accounts to avoid detection, and so on.

That is to say, any game is technically qualified to compete in all categories heavier than it specifies. Plausibly a brilliant game in the `prelude` category can win all 4 nominations.

I say this is fine — lighter games are at a disadvantage anyway, so, if one manages to win in more than one category, this only shows how good it is. Let every game compete automatically in all categories heavier than its own!

**Comment by simonmichael** [comment]
I don't see a need for this, let's keep categories separate.
