### ISSUE TITLE
"Klára" would be much more of a real Hungarian name than "Kiara"

### ISSUE THREAD

**Issue by gergoerdi** [haskell-game/tiny-games-hs#33]
https://github.com/haskell-game/tiny-games-hs/blob/8e078b3002a407f50d2bd03e723561cf664c549d/prelude/matchmaking/matchmaking.hs#L21

**Comment by gergoerdi** [comment]
@migmit

**Comment by migmit** [comment]
Well, I was kinda going back and forth on this.

On one hand, there is this page: https://hu.wikipedia.org/wiki/Kl%C3%A1ra

> Az 1990-es években a Klára ritka, a Kiara, a Klarisz és a Klarissza szórványos név volt, a 2000-es években a Klára, Klarisz és Klarissza nem szerepel a 100 leggyakoribb női név között, a Kiara 2008-ban a 72. legnépszerűbb volt.

On the other hand, in the most recent years Klára seems to gain popularity.

Anyway, @gergoerdi probably knows better than me, so, if @simonmichael thinks it's worth it, I'd be happy to make another small PR correcting that name.

**Comment by gergoerdi** [comment]
I'm pretty sure that statistics is for newborns. There is, to a first
approximation, zero Kiaras in a small village😀

**Comment by migmit** [comment]
Added a PR: https://github.com/haskell-game/tiny-games-hs/pull/34 — if @simonmichael thinks it is OK to do a small change in data after submission, it's here; if not, I'd say "Kiara" would be good enough.

**Comment by simonmichael** [comment]
Excellent. Resolved by #34.
