### ISSUE TITLE
type-and-furious: could not load Imports

### ISSUE THREAD

**Issue by simonmichael** [haskell-game/tiny-games-hs#38]
A runnability issue: currently it can't be run from outside the directory.
```
~/src/tiny-games-hs$ default/type-and-furious/type-and-furious.hs 

default/type-and-furious/type-and-furious.hs:2:1: error:
    Could not load module ‘Imports’
    it is a hidden module in the package ‘http2-3.0.3’
    it is a hidden module in the package ‘http2-3.0.3’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
2 | import Imports;printSec sec=do{when(sec>=(-0.01))$do{printf
  | ^^^^^^^^^^^^^^
```

**Comment by lsmor** [comment]
I am trying to get this. The problem is that `runghc` is locking for `Imports` in the root folder instead of `default/type-and-furious`... I am trying to execute with `stack` but I have a problem with my stack instalation. It hangs. Do you know any ghc flag to tell "Hey use this file to link"?

**Comment by simonmichael** [comment]
@lsmor it looks like you fixed this with #43. But I took the liberty of replacing the "ghc" resolver with lts like other scripts - while it worked for me, in general I believe it's a very restricted snapshot not intended for general use.

If a stack script appears to hang, it's probably installing deps the first time you run it - try adding `--verbosity=info` to the stack command to show progress.

**Comment by lsmor** [comment]
@simonmichael . Yes, apparently stack is downloading the snapshot info but with no console output, so it seems like hanging.  The reasons I picked `resolver: ghc-9.2.5` are:

- It works fast. All you need is `ghc` installed... so it doesn't "hang"  :sweat_smile:
- The `default-10-80` category precisely states "packages shipped with the compiler" which is the exact definition of such a resolver, so I thougth It was a good choice. 

Of course, feel free to change it to `lts` if that improves user experience

**Comment by simonmichael** [comment]
@lsmor I see, perhaps I shouldn't have touched it then, feel free to change back if you prefer. User experience seems the same here.

**Comment by simonmichael** [comment]
I understood your comment better ("doesn't hang"), have now changed it back.
