### ISSUE TITLE
minesweeper thumbnail still incorrect

### ISSUE THREAD

**Issue by Greg8128** [haskell-game/tiny-games-hs#42]
it seems that renaming the minesweeper thumbnail to "minesweeper.png" causes it to be replaced by the outdated one one. Could you figure out a fix so that the correct thumbnail is displayed? For reference, it should be https://files.catbox.moe/gisfhe.png, which reflects the game board being displayed

**Comment by simonmichael** [comment]
Sorry @Greg8128. I renamed it as you requested, but you are the best person to clean this up.

**Comment by Greg8128** [comment]
this got fixed on its own somehow. I'll close the issue
