### ISSUE TITLE
Nix scripts?

### ISSUE THREAD

**Issue by danwdart** [haskell-game/tiny-games-hs#55]
Wouldn't a nix script qualify? E.g.:

```haskell
#!/usr/bin/env nix-shell
#! nix-shell -p "haskell.packages.ghc92.ghcWithPackages(pkgs: with pkgs; [ blaze-svg ])" -i runghc
main = pure () {- various blaze-enabled things here -}
```

**Comment by simonmichael** [comment]
IMHO: Yes it's definitely another kind of runnable script, legal for rule 2. But, would not satisfy rule 4. ("reliable to run" and "straighforward to run" there mean for everyone, not just for nix users.)

**Comment by danwdart** [comment]
It's probably just as reliable or straightforward as stack... there are probably hardcore cabal-only users :p
Personally I use nix like one might use stack, to handle cabal, just with other stuff too.
Maybe I'll be extra sneaky and run it with even more tools and meta-win.

**Comment by simonmichael** [comment]
Submit an entry if you like.. we are here to learn!
