### ISSUE TITLE
include non-games ?

### ISSUE THREAD

**Issue by simonmichael** [haskell-game/tiny-games-hs#66]
We have a [couple](https://github.com/haskell-game/tiny-games-hs/tree/main/base/flower-seeds) of [impressive](https://github.com/haskell-game/tiny-games-hs/tree/main/hackage/lazy-march) non-playable-game entries.. call them demos. These are very much in the tradition of what you'd find in a BASIC "games" folder. But our rules call for "a playable game" and we call this a "game jam". 

Should we change the rule to say "a playable game or amusement", officially including non-games in the judging ? Or leave things as they are for this round ?

**Comment by TristanCacqueray** [comment]
Perhaps the rule could mention that user inputs and scoring are recommended but not required? I think it would be a shame to refuse such demo, but of course as the author I'm biased :)

**Comment by simonmichael** [comment]
Added "or amusement" to the rules.
