### ISSUE TITLE
7up7down could be in the `base` category with this one change!

### ISSUE THREAD

**Issue by gergoerdi** [haskell-game/tiny-games-hs#79]
https://www.reddit.com/r/haskell/comments/10we7ha/the_first_haskell_tiny_game_jam_is_now_open/j7u418x/?context=2

@akshaymankar Using `GHC.Clock.getMonotonicTimeNSec` could save you a whole weight class!

**Comment by akshaymankar** [comment]
Oh right, time is also random! Maybe I can send another PR, thanks for the tip :smile:

**Comment by akshaymankar** [comment]
This works great! Thanks. It even works without  dividing by 1000. But I suspect it might not on older computers/other OSes?
