### ISSUE TITLE
Confusion about the default/template1.hs

### ISSUE THREAD

**Issue by RimuhRimu** [haskell-game/tiny-games-hs#83]
Maybe it's because I'm new to the haskell language and its environment, but when I started my game with the [default/template1.hs](https://github.com/haskell-game/tiny-games-hs/blob/main/default/template1.hs), It starts with the `random` package, and when I submitted my game, I was told that the `random` package generally does not come with GHC #73 , so it should be moved to the hackage/category (I originally placed the game in the default category). So, my question is: Why does that template include the package `random` or why is [default/template1.hs](https://github.com/haskell-game/tiny-games-hs/blob/main/default/template1.hs) placed in the default category?

**Comment by simonmichael** [comment]
@RimuhRimu that's my fault, I originally thought random was one of the default packages. I'll fix that template, thanks for the report!

**Comment by hellwolf** [comment]
fwiw https://downloads.haskell.org/ghc/latest/docs/users_guide/packages.html

isn't random part of the list?

**Comment by simonmichael** [comment]
I believe it was in older GHCs (that doc shows GHC 6.12.1).
